version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: l10_project
    volumes:
        - ./src:/var/wwww/html
    ports:
      - "8000:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www/html
    # entrypoint: ''
    # command: >
    #   sh -c '
    #   composer install &&
    #   php artisan key:generate &&
    #   php artisan serve --host 0.0.0.0 --port 80
    #   '
    networks:
      - l10-network

networks:
  l10-network: